### ISSUE TITLE
Package Logging

### ISSUE THREAD

**Issue by janyk** [AlejandroSilva/recaptcha-verify#1]
Hi,

Great package, it works really well.

Just wondering, you seem to do a lot of logging in the index file? Is there a reason for this or could I make a pull request with them removed?

Cheers

**Comment by AlejandroSilva** [comment]
Hi, the logging in the index file are used mainly to track certain problems in the conecction if they exist. If you dont need this, or it is being used in production you can set the verbose argument to false, like this:

```
var recaptcha = new Recaptcha({
    secret: 'SECRET_KEY',
    verbose: false
});
```

**Comment by janyk** [comment]
Oh right, silly me. Thanks!
