### ISSUE TITLE
Package name still wrong on npmjs.com.

### ISSUE THREAD

**Issue by dudewheresmycode** [AlejandroSilva/recaptcha-verify#3]
Just a heads up. I'm guessing it just hasn't been published to npmjs.org since the pull request.

![image](https://cloud.githubusercontent.com/assets/3523761/24325842/fe0f3faa-115e-11e7-9c3b-d622b4ab3916.png)

**Comment by AlejandroSilva** [comment]
I didn't know that has to change the package version in order to npmjs to update the README.md

thanks for notice it! the npmjs readme is now updated ;)
