### ISSUE TITLE
It logs: reCAPTCHA > base path: /recaptcha/api/siteverify?secret=

### ISSUE THREAD

**Issue by jongood01** [AlejandroSilva/recaptcha-verify#4]
The package logs: reCAPTCHA > base path: /recaptcha/api/siteverify?secret=.... this to the console every time it is initiated. This is costly for systems like cloud functions that charge for logs.

**Comment by AlejandroSilva** [comment]
Hi @jongood01 , the logging in the index file are used mainly to track certain problems in the connection if they exist. If you don't need this, or it is being used in production you can set the verbose argument to false, like this:

```
var recaptcha = new Recaptcha({
    secret: 'SECRET_KEY',
    verbose: false
})

```
I will close this issue as it's a duplicated of #1
